### ISSUE TITLE
Option to build to js

### ISSUE THREAD

**Issue by gpoitch** [gristlabs/ts-interface-builder#12]
I can currently achieve this like this:
`ts-interface-builder my-types.d.ts && tsc my-types.d-ti.ts && rm my-types.d-ti.ts`

Thought it might be a useful option instead:
`ts-interface-builder my-types.d.ts --js`

I find this useful for runtime validation in regular js projects (thanks!).  The generated files aren't really utilizing any useful typescript anyway.

**Comment by dsagal** [comment]
I can see that being convenient. Seems doable with adding a step like the following to the code, before writing out the file:

```
    const result = ts.transpileModule(generatedCode, {
      compilerOptions: { module: ts.ModuleKind.CommonJS }
    });
```

We may need to support things like `--js=ES5|ES2015|ESNEXT|etc` (as for `tsc --target`), since different people may need different styles of JS output.

I'd be open to a pull request :)

**Comment by zenflow** [comment]
> We may need to support things like --js=ES5|ES2015|ESNEXT|etc (as for tsc --target), since different people may need different styles of JS output.

@dsagal I don't think we need an option for the target *language*, because our generated TS code doesn't use many language features beyond basic **pre**-ES5 features (e.g. method calls, array/object/number/string literals, etc.). Unless I am mistaken, there are only 2 cases:

1. The type annotation near the end of the file ( `const exportedTypeSuite: t.ITypeSuite = {`)
2. The module format. ES5 and earlier do not include ES modules.

Therefore, the user really only needs the following configuration options:
1. TS or JS?
2. If JS, what module format?

Note that the 2nd config option is actually mostly practically useful for generating code to be run on NodeJS (since ES modules are not supported by Node.js), but also allows us to generate JS code that is pre-ES6 compatible.

---

I also propose that instead of compiling the generated code with TypeScript, we just generate the code in the requested format:
1. If user requests JS, simply omit the `t.ITypeSuite` type annotation (and any other type annotations or TypeScript syntax, but I think that's the only one).
2. If user requests CommonJS (CJS) module format, generate the code in that format instead of ES modules.

This will be better because:
1. Less computationally intensive
2. We can easily control the CJS output

The second point gives us the opportunity to output CJS in the simplest and most parse-able style: a single export of a single expression. Here's what I mean:

```js
var t = require('ts-interface-checker');
module.exports = {
  SomeAlias: t.name("number"),
};
```

This output can be easily manipulated.

This is important for my solution for #22. If this isn't accepted, I would need to find another way to extract the type suite as a single object literal expression. 

Thanks for reading! PR incoming to implement this! 😀

**Comment by dsagal** [comment]
This all sounds good!
